const pizzas = [
  {
    name: "Funghi",
    price: 15,
    ingredients: "Tomato sauce, Mushrooms, Mozzarella",
    photo: "pizzas/funghi.jpg",
    hashtag: "Yummi",
    color: "yellow",
    emoji: "✅",
  },
  {
    name: "Mexican",
    price: 20,
    ingredients: "Chilli, Beef, Jalapeños, Cheese",
    photo: "pizzas/focaccia.jpg",
    hashtag: "Spicy",
    color: "red",
    emoji: "🌶️",
  },
  {
    name: "Pepperoni",
    price: 18,
    ingredients: "Tomato sauce, Mozzarella, Pepperoni",
    photo: "pizzas/spinaci.jpg",
    hashtag: "Classic",
    color: "orange",
    emoji: "🍕",
  },
  {
    name: "Margherita",
    price: 12,
    ingredients: "Tomato sauce, Mozzarella, Basil",
    photo: "pizzas/margherita.jpg",
    hashtag: "Simple",
    color: "green",
    emoji: "🍅",
  },
  {
    name: "Hawaiian",
    price: 19,
    ingredients: "Ham, Pineapple, Mozzarella",
    photo: "pizzas/salamino.jpg",
    hashtag: "Sweet",
    color: "yellow",
    emoji: "🍍",
  },
  {
    name: "Quattro Formaggi",
    price: 22,
    ingredients: "Mozzarella, Gorgonzola, Parmesan, Fontina",
    photo: "pizzas/prosciutto.jpg",
    hashtag: "Cheesy",
    color: "white",
    emoji: "🧀",
  },
  {
    name: "Diavola",
    price: 21,
    ingredients: "Tomato sauce, Spicy salami, Mozzarella",
    photo: "pizzas/focaccia.jpg",
    hashtag: "Hot",
    color: "red",
    emoji: "🔥",
  },
  {
    name: "Vegetarian",
    price: 17,
    ingredients: "Bell peppers, Onions, Mushrooms, Olives",
    photo: "pizzas/vegetarian.jpg",
    hashtag: "Healthy",
    color: "green",
    emoji: "🥦",
  },
  {
    name: "BBQ Chicken",
    price: 24,
    ingredients: "BBQ sauce, Chicken, Red onion, Mozzarella",
    photo: "pizzas/bbq_chicken.jpg",
    hashtag: "Savory",
    color: "brown",
    emoji: "🍗",
  },
  {
    name: "Capricciosa",
    price: 20,
    ingredients: "Ham, Mushrooms, Artichokes, Olives",
    photo: "pizzas/capricciosa.jpg",
    hashtag: "Italian",
    color: "olive",
    emoji: "🍖",
  },
  {
    name: "Napoletana",
    price: 15,
    ingredients: "Tomato sauce, Anchovies, Capers, Oregano",
    photo: "pizzas/napoletana.jpg",
    hashtag: "Mediterranean",
    color: "blue",
    emoji: "🌊",
  },
  {
    name: "Spinach & Ricotta",
    price: 18,
    ingredients: "Spinach, Ricotta, Mozzarella",
    photo: "pizzas/spinach_ricotta.jpg",
    hashtag: "Vegetarian",
    color: "green",
    emoji: "🌱",
  },
  {
    name: "Truffle",
    price: 28,
    ingredients: "Truffle oil, Mushrooms, Mozzarella, Parmesan",
    photo: "pizzas/truffle.jpg",
    hashtag: "Gourmet",
    color: "black",
    emoji: "🍄",
  },
  {
    name: "Tuna",
    price: 19,
    ingredients: "Tuna, Onions, Capers",
    photo: "pizzas/tuna.jpg",
    hashtag: "Seafood",
    color: "blue",
    emoji: "🐟",
  },
  {
    name: "Buffalo Mozzarella",
    price: 25,
    ingredients: "Tomato sauce, Buffalo mozzarella, Basil",
    photo: "pizzas/buffalo_mozzarella.jpg",
    hashtag: "Authentic",
    color: "white",
    emoji: "🥛",
  },
  {
    name: "Prawn",
    price: 27,
    ingredients: "Prawns, Garlic, Chilli, Mozzarella",
    photo: "pizzas/prawn.jpg",
    hashtag: "Seafood",
    color: "pink",
    emoji: "🍤",
  },
  {
    name: "Cheeseburger",
    price: 22,
    ingredients: "Beef, Cheddar, Pickles, Onion",
    photo: "pizzas/cheeseburger.jpg",
    hashtag: "Fusion",
    color: "orange",
    emoji: "🍔",
  },
  {
    name: "Smokey Bacon",
    price: 23,
    ingredients: "Bacon, Smokey BBQ sauce, Onions",
    photo: "pizzas/smokey_bacon.jpg",
    hashtag: "Smokey",
    color: "brown",
    emoji: "🥓",
  },
  {
    name: "Prosciutto & Rocket",
    price: 26,
    ingredients: "Prosciutto, Rocket, Parmesan",
    photo: "pizzas/prosciutto_rocket.jpg",
    hashtag: "Fresh",
    color: "green",
    emoji: "🍃",
  },
  {
    name: "Garlic & Herb",
    price: 14,
    ingredients: "Garlic, Herbs, Mozzarella",
    photo: "pizzas/garlic_herb.jpg",
    hashtag: "GarlicLovers",
    color: "white",
    emoji: "🧄",
  },
  {
    name: "Carbonara",
    price: 21,
    ingredients: "Cream, Bacon, Parmesan, Egg",
    photo: "pizzas/carbonara.jpg",
    hashtag: "PastaInspired",
    color: "yellow",
    emoji: "🥚",
  },
  {
    name: "Pollo e Pesto",
    price: 24,
    ingredients: "Chicken, Pesto, Mozzarella, Parmesan",
    photo: "pizzas/pollo_pesto.jpg",
    hashtag: "Herby",
    color: "green",
    emoji: "🌿",
  },
  {
    name: "Sausage & Peppers",
    price: 22,
    ingredients: "Sausage, Bell peppers, Onions, Mozzarella",
    photo: "pizzas/sausage_peppers.jpg",
    hashtag: "Hearty",
    color: "red",
    emoji: "🌶️",
  },
  {
    name: "Eggplant & Feta",
    price: 20,
    ingredients: "Grilled eggplant, Feta, Olive oil",
    photo: "pizzas/eggplant_feta.jpg",
    hashtag: "Mediterranean",
    color: "purple",
    emoji: "🍆",
  },
  {
    name: "Seafood Deluxe",
    price: 29,
    ingredients: "Prawns, Calamari, Mussels, Garlic",
    photo: "pizzas/seafood_deluxe.jpg",
    hashtag: "OceanFlavor",
    color: "blue",
    emoji: "🦞",
  },
  {
    name: "Calzone",
    price: 19,
    ingredients: "Ham, Mozzarella, Mushrooms, Tomato sauce",
    photo: "pizzas/calzone.jpg",
    hashtag: "Folded",
    color: "brown",
    emoji: "🥟",
  },
  {
    name: "Pumpkin & Goats Cheese",
    price: 23,
    ingredients: "Roasted pumpkin, Goats cheese, Rocket",
    photo: "pizzas/pumpkin_goats_cheese.jpg",
    hashtag: "Fall",
    color: "orange",
    emoji: "🎃",
  },
  {
    name: "Gorgonzola & Pear",
    price: 25,
    ingredients: "Gorgonzola, Pear, Walnuts, Honey",
    photo: "pizzas/gorgonzola_pear.jpg",
    hashtag: "SweetAndSavory",
    color: "blue",
    emoji: "🍐",
  },
  {
    name: "Greek",
    price: 22,
    ingredients: "Feta, Olives, Tomatoes, Cucumber, Oregano",
    photo: "pizzas/greek.jpg",
    hashtag: "SaladPizza",
    color: "white",
    emoji: "🥗",
  },
  {
    name: "Chicken Tikka",
    price: 24,
    ingredients: "Chicken tikka, Red onion, Coriander",
    photo: "pizzas/chicken_tikka.jpg",
    hashtag: "IndianFlavor",
    color: "orange",
    emoji: "🍛",
  },
];

export default pizzas;
